package com.android.teams.domain.exception;

import java.lang.System;

@kotlin.Metadata(mv = {1, 4, 1}, bv = {1, 0, 3}, k = 2, d1 = {"\u0000\u000e\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0003\n\u0000\u001a\u0010\u0010\u0000\u001a\u00020\u00012\b\u0010\u0002\u001a\u0004\u0018\u00010\u0003\u00a8\u0006\u0004"}, d2 = {"traceErrorException", "Lcom/android/teams/domain/model/ApiError;", "throwable", "", "app_debug"})
public final class ApiErrorHandlerKt {
    
    /**
     * Trace exceptions(api call or parse data or connection errors) &
     * depending on what exception returns [ApiErrorf]
     */
    @org.jetbrains.annotations.NotNull()
    public static final com.android.teams.domain.model.ApiError traceErrorException(@org.jetbrains.annotations.Nullable()
    java.lang.Throwable throwable) {
        return null;
    }
}